src/general.rs

This addresses a null pointer exception that is thrown by the Eclipse JDT language server (https://github.com/eclipse/eclipse.jdt.ls) when the workspace has no capabilities defined.
The null pointer is thrown here: https://github.com/eclipse/eclipse.jdt.ls/blob/f364a491a701add3639c42803b0afc8da6df4b50/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java#L95
Which is called from here: https://github.com/eclipse/eclipse.jdt.ls/blob/edffe44f04172cc05174df43f1acf220427f202d/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#L157
I can provide any additional information required, etc.
Edit:
Also note the typo in WorkspaceClientCapabilities. The typo is on their end: …

Defined WorkspaceClientCapabilites to fix Eclipse JDT LS errors

---

src/diagnostics.rs

Currently it's difficult to tell errors apart from warning without moving the cursor over the problematic section. This changes the face used to highlight diagnostics other than actual warnings to Information.

Only errors will be highlighted with the Error face

---

README.asciidoc

I've created an AUR package to automate/structure installation for ArchLinux users here: https://aur.archlinux.org/packages/kak-lsp-git/ - this adds a reference to it in the README.
Regarding the package itself, happy to incorporate any suggestions / changes to the install process. You can see the PKGBUILD file [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kak-lsp-git).

Reference AUR package

---

README.asciidoc
kak-lsp.toml
rc/lsp.kak
src/editor_transport.rs
src/main.rs
src/types.rs
src/util.rs

Sketch of #36 implementation.
In a nutshell:
* If `-s <SESSION>` command-line option is provided in server mode (default one, w/o `--kakoune` or `--request` flag) then kak-lsp tries to bind unix socket under `$TMPDIR/kak-lsp` dir. Mode 0700 is set to directory. In case socket already exists kak-lsp tries to connect to it. If connection is successful, current instance just exits because server is already running. Otherwise it tries to remove dead socket and bind own.
* `--request` mode interprets `-s` option as a destination. It doesn't try to start server if it's not running.
* Integration with Kakoune basically looks like:
```
%sh{kak-lsp --kakoune -s $kak_session}
lsp-start
```
`lsp-start` is just a generated wrapper forking `kak-lsp` with the same session and diverting output to …

Draft implementation of sessions (via unix sockets) support

---

rc/lsp.kak
src/language_features/completion.rs

While using a php language server (which I also added to the wiki). I noticed that completion of variables prefixed with a `$` results in something like `$\$variable`.
This is the result of two things in the code.
In rc/kak.lsp, the regex selecting the word that is to be replaced by the completion only takes \w characters. 
I changed it so that it also selects the leading `$`.
This results in variables completed to `\$variable`, which is a bit better.
In src/language_features/completion.rs the characters `[:|$]` are escaped.
I do not see a problem with removing this escaping, so I would gladly see pointed out why this escaping is necessary.
For now, disabling the escaping for the return entry fixes the issue.

Fix completion of dollar prefixed variables

---

kak-lsp.toml

The "go to definition" and completions are useful even for zsh, so until there is a dedicated zsh language server, let's keep this enabled for zsh as well.

Add bash language server

---

rc/lsp.kak
src/diagnostics.rs

Ive been missing this for some time, its really useful when scrolling through a file looking for errors.
Currently theres no way to set individual faces for each line spec, so errors and warnings both use the same face `LineFlagErrors´. However, the characters are customizable with the options `lsp_diagnostics_line_{error,warning}_sign`. It defaults to `*` for errors and `!` for warnings. Then the user can feel free to use whatever fancy unincode character they want.
I dont really know anything about rust, so i may have duplicated a little too much code, but it works, and is probably easy to clean up

Add line-flags for diagnostics

---

src/language_features/formatting.rs

(Tested with Typescript)
Before:
`const j= 1234;`  
formats to
`const    1234;`
Now:
`const j= 1234;`
formats to
`const j = 1234;`

Correct behaviour when formatting change is same line and character

---

src/controller.rs

According to the spec, the client must send initialized notification
before sending any other requests or notifications.
https://microsoft.github.io/language-server-protocol/specification#initialized
>The initialized notification is sent from the client to the server after the client received the result of the initialize request but before the client is sending any other request or notification to the server. The server can use the initialized notification for example to dynamically register capabilities. The initialized notification may only be sent once.

Send initialized notification

---

src/context.rs
src/controller.rs
src/general.rs

I took a quick peek at the code and I think I've identified one of the major sources of complexity here: the `posoned_tx_rx` pattern. It is used to cancel stuff all over the place. However in Rust we have a wonderful tool for cancellation: RAII (I've even [blogged](https://matklad.github.io/2018/03/02/stopping-a-rust-worker.html) about it). 
The main idea is that, instead of doing `select!(receiver, poison)`, we just do `for msg in receiver` and treat a closed receiver as a shutdown signal. A cool thing about this pattern is that it automatically works when the sender is dropped due to panic. 
I've applied it only in one instance, but it should be applicable to other uses of poisoned channels as well. 
I am also not sure that this particular patch actually works: I don't have a good …

Simplify poisoning pattern

---

src/context.rs
src/controller.rs
src/general.rs
src/main.rs
src/session.rs
src/types.rs
src/util.rs

@matklad have I applied you suggestions properly? I think I got the idea, but there are could be some subtle nuances which I could have missed. Though I tested changes manually and they seem to work correctly for the most common cases, and the only hole left is exiting by timeout (it's still a hard process::exit, I plan to fix it soon (and now it's much easier to do!), just want to do it together with pid/socket cleanup issue).
I was again surprised how well Rust compiler supports such refactors. Literally, I fearlessly moved big chunks of code around, fixed compiler errors, and it worked!

simplify controllers lifecycle; close #108

---

src/main.rs

It looks like `rls` does not work correctly if cwd was changed to `/`. I can hardly see downsides of deamonizing in the cwd, so I propose this as a patch, and I will fill an issue against rls.

Daemonize in a current working directory

---

README.asciidoc

I added `kak-lsp` to the official package repository for Arch Linux. 
Hopefully other distros will package it too at some point, so I proactively created a whole new section `Package managers` 😄

Update install instructions for Arch Linux

---

rc/lsp.kak

Fixes #137.
I filed https://github.com/mawww/kakoune/issues/2618 about `prompt` mysteriously not working inside `eval -draft`.

Make the lsp-rename-prompt prompt default to the current name.

---

rc/lsp.kak

shell stderr: <<<
sh: line 3: [: =: unary operator expected
sh: line 7: [: =: unary operator expected
>>>

Fix error when executing lsp-find-error without arguments

---

README.asciidoc
plugin.kak
rc/lsp.kak

Ok. So I've read some code, and come to conclusion that there's no need in `plugin.kak` at all.
Your plugin is now loading perfectly fine with `plug`, and can be loaded in the same way without it by simply sorcing `lsp.kak`:
```kak
plug "andreyorst/kak-lsp" do %{
cargo build --release
cargo install
}
```
This PR fixes #117.
I've also did bit of refactoring by replacing all short commands with standard ones, like `decl` to `declare-option`. Are there any tests for kakscript so I could check if I didn't break anything?

Proper loading by plugin managers

---

rc/lsp.kak
src/controller.rs
src/text_sync.rs
src/types.rs

kak-lsp is used to read a file's content from a filesystem on `didOpen` before sending it to a language server, and this is something that does not work in case we are dealing with newly created (unsaved) file. In order to fix that problem, we need to send a buffer context from kakoune directly to kak-lsp, similarly to `didChange` message.
Closes #156

 lsp-did-open: send text from kakoune to kak-lsp

---

rc/lsp.kak

mappings that are executed from `goto` mode are displayed in history.

Add missing space to mappings to discard history

---

kak-lsp.toml

[Go modules](https://github.com/golang/go/wiki/Modules) were introduced in 1.11 in 2018 and will become the default in 1.13 this year. Many people have already switched to using them. 
`go-langserver` [doesn't support](https://github.com/sourcegraph/go-langserver/issues/316) Go modules, thus [`bingo` was born](https://github.com/sourcegraph/go-langserver/issues/316#issuecomment-441412860). I've tested it today, works quite well, and indeed supports Go modules.
Go devs are also working on the official language server called `golsp`, but it is still in very early development.
I propose to change the default to `bingo`, and in future reconsider switching to the official `golsp` once it becomes stable.
See also [Differences between go-langserver, bingo, …

Use bingo for Go

---

README.asciidoc

This is weird, but today my cargo ranted on me that I'm not able to use `cargo install`:
```
error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead
```

add --path . to plug installation method

---

README.asciidoc
rc/lsp.kak

I was having difficulty getting diagnostic flags to show up, and found it frustrating that  `lsp-diagnostic-lines-enable` sounded like it should do what I wanted, but instead it just complained "wrong argument count".
It turns out my actual problem was I hadn't called `lsp-enable`, but I figure more detailed docstrings never hurt.

Add docstrings for the various diagnostics-related commands.

---

src/project_root.rs
src/session.rs

Allow per language marker files to be overridden by directly specifying
the project root for a given buffer. When searching for the project root
for a buffer first see if there are any environment variables prefixed
by `KAK_LSP_PROJECT_ROOT_%LANG%`. If so then iterate over all matching
variable values checking if they are a prefix of the path to the current
buffer. If so the first matching prefix is selected as the project root,
else return the buffers path. If there are no matching environment
variables then proceed as before.

Allow project roots to be specified by environment

---

README.asciidoc

In #161, the lsp_tab_size option was removed, since Kakoune already provides the tabstop option. However, removing this option from the documentation leaves no clue that it affects the lsp-formatting command, so we update the lsp-formatting documentation to mention the options it uses.

README: lsp_tab_size was replaced with the standard tabstop option.

---

rc/lsp.kak
src/context.rs
src/controller.rs
src/language_features/ccls.rs
src/types.rs

Rust Language Server sends useful progress messages to communicate what it is doing, and the VS Code rust extension displays them in the statusbar.
This allows users to override the `lsp-handle-progress` command. For example: 
```
declare-option -hidden str modeline_progress ""
define-command -hidden -params 4 -override lsp-handle-progress %{
set global modeline_progress %sh{
echo $1${2:+": $2"}${3:+" $3%"}${4:+" ✓"}
}
}
```
And then put `%opt{modeline_progress}` in your `modelinefmt` to see what RLS is doing.

Send window/progress messages to editor

---

src/context.rs
src/controller.rs
src/diagnostics.rs
src/general.rs
src/language_features/ccls.rs
src/language_features/completion.rs
src/language_features/definition.rs
src/language_features/document_symbol.rs
src/language_features/formatting.rs
src/language_features/hover.rs
src/language_features/references.rs
src/language_features/rename.rs
src/language_features/signature_help.rs
src/text_sync.rs
src/types.rs
src/workspace.rs

Changes ctx.call and ctx.notify to take the request type as a generic parameter, which simplifies calling and allows automatic parsing of the response type, and also eliminated the need for dispatch_server_response.
Created types to represent CCLS requests.
Also, EditorMeta was being passed by reference and then cloned frequently even though the caller had no need for it anymore. Changed to move instead and was able to remove lots of clone()s.
This is related to #110 but does not complete it.

Use callbacks instead of a separate dispatch function for responses

---

src/language_features/ccls.rs
src/language_features/completion.rs
src/language_features/definition.rs
src/language_features/formatting.rs
src/language_features/references.rs
src/language_features/rename.rs
src/language_features/signature_help.rs
src/project_root.rs
src/text_sync.rs
src/workspace.rs

Also, trying to keep params separate from req_params. The name changing purpose was confusing.

Avoid unnecessary cloning

---

rc/lsp.kak
src/context.rs
src/controller.rs
src/general.rs
src/language_features/codeaction.rs
src/language_features/mod.rs
src/workspace.rs

Enables basic support for code actions. I haven't tested this extensively, but it is enough to allow RLS's "Deglob Imports" action to work correctly.
In the future, I'd like to make it possible to show the number of available code actions in the modeline, maybe by setting a list option instead of immediately executing the menu command?

CodeAction support

---

kak-lsp.toml

Nim project is defined by the file with `.nimble` extension. I suppose i cannot add a substring as valid root?

Add Nim support

---

src/context.rs
src/controller.rs

This removes code working around the lack of `Box<FnOnce>`!
If kak-lsp previously had a minimum supported rust version, this raises that to 1.35.0. Understandable if this isn't wanted because of that. If that's fine, this should be a pretty small change.

Use Box<FnOnce>, stabilized in 1.35.0

---

rc/lsp.kak
src/text_edit.rs

Currently, text is isnerted before the cursor when at column 0 and after the cursor at other columns. This is not correct, though: it "skips" over the position between columns 1 and 2 (in Kakoune coordinates) and makes inserts that aren't at the beginning of a line off by 1. Text should instead always be inserted before the cursor in Kakoune, not just when at the beginning of the line.
As far as I can see, `KakouneTextEditCommand::InsertAfter` isn't needed at all: cursors in Kakoune can refer to the newline character (or end-of-file if there is no newline at the end of the file) of each line, so even if the LSP column is at the end of the line, the insert can still be represented as an insertion before the cursor in Kakoune. (I hence removed it and the corresponding …

Insert before the cursor for all text edits

---

rc/lsp.kak

Fixes #245 
Other notable changes:
* lsp-did-change was not operating asynchronously, but lsp-did-open was. They are now both asynchronous
* the three chained sed calls have been merged into one (I think that should be portable? Would be nice if on macos could test, since afaik it has noticeable differences)
To test this, you can check that with a file bigger than 128kib, changing the buffer content causes both kak-lsp and the language server to use _some_ cpu. Before, it did not and kept idling.
However jumping to definitions was working before, even on files that big. It's not entirely clear to me what didChange is supposed to do, but it does not seem entirely necessary?

Pass buffer content using stdio instead of environment variables

---

kak-lsp.toml

Bingo has been discontinued and go-langserver is very slow (at least on go.mod projects), the best drop-in replacement is gopls (https://github.com/golang/tools/tree/master/gopls).

Replace bingo with gopls

---

src/language_features/codeaction.rs

Following change adds diagnostics to codeAction request and is required to make code actions work with eclipse jdt.ls (along with [this PR to jdt.ls](https://github.com/eclipse/eclipse.jdt.ls/pull/1278)).
Note: I actually do not know rust, please point out if there is a better way to write it.

Code action with diagnostics

---

rc/lsp.kak
src/controller.rs
src/language_features/eclipse_jdt_ls.rs
src/language_features/mod.rs

Adds ejdtls-organize-imports command to invoke java.edit.organizeImports command of eclipse.jdt.ls.

eclipse.jdt.ls organize imports extension

---

kak-lsp.toml

I couldn’t think of any sensible roots so I simply choose `.git`. Server is [texlab](https://github.com/latex-lsp/texlab).

Add LaTeX support

---

rc/lsp.kak

The missing quotes prevented the command from working if the file path contains spaces.

Fix a quoting issue in lsp-find-error

---

kak-lsp.toml

We need to use a shell to find the correct path to the dart analysis
server source file. This should be in a known location relative to the
dart binary, regardless of whether the dart sdk was installed
stand-alone or part of the flutter toolkit. However the dart sdk and
binary location could be anywhere since it's commonly user installed
from source.

Update dart language server command

---

rc/lsp.kak
src/context.rs
src/controller.rs
src/language_features/semantic_highlighting.rs

`clangd` now implements incremental highlighting, so i implemented it here.
It stores the updated lines in the context, and then calls `lsp-update-semantic-highlighting` in the editor, which sends the current semhl option to `kak-lsp`. This is then parsed, and any regions on updated lines are removed, and the new regions are added.
This is made a lot easier than one would think, because the semhl is sent from the server one line at a time, so no fancy overlap checking is requried.
Tested a little bit with clangd, it appears to work, and correctly removes old regions.

Support incremental semantic highlighting

---

README.asciidoc

The instructions in the README do not help if what you want to troubleshoot is a panic, or if you want to run a debugger. This provides an alternative way to run `kak-lsp` that makes troubleshooting more like usual daemon software.

Add help for troubleshooting crashes

---

README.asciidoc

It turns out that you can start kak-lsp before the Kakoune session is actually running, which drastically simplifies the instructions for launching kak-lsp outside Kakoune.

Easier instructions for crash troubleshooting

---

README.asciidoc
rc/lsp.kak
src/controller.rs
src/language_features/mod.rs
src/language_features/rust_analyzer.rs
src/types.rs

Requires https://github.com/mawww/kakoune/pull/3440.
To test:
- Use [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer)
- `hook global NormalIdle .* rust-analyzer-inlay-hints`
- `hook global InsertIdle .* rust-analyzer-inlay-hints`
- Wait (rust-analyzer takes a while before it starts sending them)
I'm not sure what the best way to make these automatically requested is.

rust-analyzer inlay hints

---

README.asciidoc
kak-lsp.toml
rc/lsp.kak
src/controller.rs
src/language_features/mod.rs
src/language_features/semantic_tokens.rs
src/types.rs

The successor to the previous proposed semantic highlighting API.
Tested with rust-analyzer, I think clangd also has support.
Test with `:lsp-semantic-tokens`. Like my other PR, I'm not sure the right way to run this automatically is.

proposed Semantic Tokens support

---

README.asciidoc

I left these out because they seemed wasteful but editing in normal mode actually needs these.

Add NormalIdle for inlay hint/semantic tokens instructions

---

src/language_features/completion.rs

This is a targeted fix for the cases where Kakoune insertion would do
exactly the same as the text edit.
If the language server sends simple textEdit objects that replace
precisely the token left of the cursor, then we can just pass them to
Kakoune as normal completions. This is strictly better than using the
completion's label, because Kakoune's completion engine does exactly
what the text edit is supposed to do.
See below for an example that is not fixed by this commit. I believe
it makes sense to have this partial support until #40 is properly
implemented, because it seems safe and fixes what is arguably the most
common completion scenario: completing the suffix of a token.
Reproduce with this example C file using ccls. Cursor is `|`.
void foobar(){}
void main(){
fo|	// Fixed: …

Use textEdit completions that replace token left of cursor

---

src/general.rs

This was missed two years ago, when fixed for the completion. This
ensures that e.g. gopls no longer tries to send us Markdown.
Overlooked for ... almost 2 years :) https://github.com/ul/kak-lsp/issues/69#issuecomment-404334258

Request plain-text content for hover and signature information

---

README.asciidoc
rc/lsp.kak
src/diagnostics.rs

This PR adds "inlay diagnostics" (because the name "inline diagnostics" is already taken):
It works well sometimes and saves time hovering over lines for errors:
But it's unfortunately also quite buggy:
I'm not sure if it should be merged, but I'm posting it here in case anyone has ideas on how to make it work better, or if anyone wants to use it anyway (I will), since hovering over lines is a big pain (in my opinion).

Inlay diagnostics support

---

src/general.rs

Hi
When executing `lsp-capabilities`, the mapping for `lsp-definition` appears in the infobox but the one for `lsp-references` is missing

doc: mention that lsp-references is mapped to gr by default

---

README.asciidoc

Hello
In Kakoune commands like `grep-previous-match` or `grep-next-match`
(and their `make-*`) equivalent are hardcoded to search for a buffer
named `*grep*` or `*make*`.
Unfortunately it means that they can't be used for buffers with meaningful
names like `*references*`. So I tried to clarify this point.
In #169 dedicated commands where added for references and symbols,
I've added them explicitly.
In a future PR, for consistency, we may want to add the same for
`*implementations*` and `*diagnostics*`. Beware, there's a nuance with
the last one as it is a `make` not a `grep` buffer.

doc: mention *-previous-match and *-next-match commands

---

src/diagnostics.rs

This prevents highlighting the diagnostic itself in the EOL char face.

Inlay diagnostics: use the character before the newline

---

kak-lsp.toml

[haskell-ide-engine](https://github.com/haskell/haskell-ide-engine/) added `hie-wrapper` two years ago, to identify the right ghc version to use.

Update default haskell config to use `hie-wrapper`

---

rc/lsp.kak

I noticed when I had set the lsp_hover_max_lines option my diagnostics in hover were not showing, this change fixed it for me.

fix diagnostics in hover when lsp_hover_max_lines > 0

---

src/diagnostics.rs
src/language_features/semantic_tokens.rs

Ran `cargo test`. These fixups were needed for `master` to compile.
Not 100% sure why type inference didn't work on these literals.
Needed to use u64 to get access to u64::MAX.

Rust 1.41.0 fixups

---

rc/lsp.kak

[This issue](https://github.com/mawww/kakoune/issues/3507)
And overall why use `%val` for registers, when everywhere else there's `%reg` already?

Change val to reg, to fix snippets on newer versions of kak.

---

src/context.rs
src/controller.rs

This adds a context method, `batch_call`, which you can pass a `Vec` of language-server requests, and a callback, which is passed an accumulated list of the responses.
This allows us to, for example, flatten responses, so we have a single history item in kakoune, as we want in https://github.com/ul/kak-lsp/pull/347
Note that the responses are not necessarily in the same order as the requests.
I couldn't think of a use case for that, so KISS.
If anyone needs this behavior, it's trivial to implement.

LS response bucketing

---

README.asciidoc
src/diagnostics.rs
src/main.rs
src/position.rs

Also adds a panic hook, since the integer overflow crashed the process without any information in the log.

Fix inlay diagnostics for gopls

---

src/project_root.rs

Tweak the root finding logic to search for roots in order of their appearance in
the list.
This is useful when you have subprojects underneath your main project directory,
but would like to set the root to the parent project directory.
For example, we might have nested haskell subprojects like
```
.
├── project.cabal
├── hie.yaml
├── src
│  └── ...
├── subproject
│  ├── subproject.cabal
│  └── ...
└── ..
```
Even though there is a `subproject.cabal` file, we want to give preference to a
`hie.yaml` file which, if it exists, tells the language server exactly how to
load the project. This is not the case with a `*.cabal` file, where the language
server has to do some guesswork (which might fail).
With this patch, we can achieve the desired behaviour by setting the haskell
configuration roots …

Give preference to roots according to their position in configuration list

---

rc/lsp.kak
src/controller.rs
src/general.rs
src/language_features/mod.rs
src/language_features/range_formatting.rs
src/session.rs
src/types.rs

Adds support for `textDocument/rangeFormatting`, which formats the current selections.
Tested with `haskell-language-server`.
~Because the `language-server-protocol` doesn't support batching, we're using one message per selection. This means we also get a history item per selection :shrug:.~

Add selection formatting

---

rc/lsp.kak

Unescapes `test=foo\=bar` to `key: test` and `value: foo=bar`.

Properly unescape = in key-value pair

---

rc/lsp.kak

The following pull request removes the dependency on **bash** by using **here-doc** instead of **here-string** as discussed [here](https://github.com/ul/kak-lsp/commit/23e229eb1ba649697af0c9895001cb161e3d4d04#commitcomment-40231590).
The fix has been tested on **MacOS** using `/bin/dash` as `KAKOUNE_POSIX_SHELL`.

Remove bash dependency by replacing here-string '<<<' with here-doc '<<'

---

Cargo.lock
Cargo.toml
src/general.rs
src/language_features/ccls.rs
src/language_features/completion.rs
src/language_features/document_symbol.rs
src/language_features/goto.rs
src/language_features/highlights.rs
src/language_features/hover.rs
src/language_features/signature_help.rs

Required for clangd 11, which relies on `TextDocumentSyncOptions.save` to be a boolean in lsp 3.15+

Update to lsp-types 0.77.0

---

Cargo.lock
Cargo.toml
src/general.rs
src/language_features/ccls.rs
src/language_features/completion.rs
src/language_features/document_symbol.rs
src/language_features/goto.rs
src/language_features/highlights.rs
src/language_features/hover.rs
src/language_features/signature_help.rs

Show semantic highlighting and semantic token info in `lsp-capabilities`
The available scopes, types and modifiers can be quite useful for configuring faces, so i display them there as well.
The "old" eclipse Theia semantic highlighting:
The "new" semantic tokens:
This is based on my other pr #373, since clangd 11 is the only server I use with semantic tokens support afaik.
A way to access lsp-capabilities and check for specific capabilities might be useful as well for configuration, like automatically adding the `lsp-semantic-token` hooks if the server supports it

Add semhl capabilities

---

kak-lsp.toml

Use rustup to figure out what is the active toolchain and use that binary
Added rust-analyzer but commented as it is only available in nightly
by using rust-analyzer-preview

Rust use component for active toolchain

---

kak-lsp.toml

cquery development has been abandoned, and clangd is both widely available (as part of clang) and has the resources of the LLVM project behind it.
Fixes #380.

kak-lsp.toml: Default to clangd instead of cquery.

---

rc/lsp.kak

Currently showing diagnostics and other actions override the default yank/copy/delete register.
This fixes that

save the " register when showing diagnostics and other buffers

---

kak-lsp.toml

This adds support for Nix files, by way of [rnix-lsp](https://github.com/nix-community/rnix-lsp). I also took the opportunity to sort the existing language config blocks by alphabetical order, since that was becoming increasingly arbitrary.

Add support for Nix

---

Cargo.lock
Cargo.toml
rc/lsp.kak
src/controller.rs
src/general.rs
src/language_features/semantic_tokens.rs

Updates lsp-types to 0.80.0
Works with clangd 12 (latest master)

Update semantic tokens to LSP 3.16

---

rc/lsp.kak
src/controller.rs
src/language_features/clangd.rs
src/language_features/mod.rs

Implement `textDocument/switchHeaderSource` as specified by https://clangd.llvm.org/extensions.html#switch-between-sourceheader

clangd-switch-source-header

---

kak-lsp.toml

At the moment there are two language server implementations. 
I would pick the [offical](https://github.com/hashicorp/terraform-ls) one, since it will work with more terraform versions.

Add official terraform language server

---

src/diagnostics.rs

Commit 155b21f (Inlay diagnostics support) copies an eval which is used
to interpret %opt[] tags in line_flags.  It's not necessary here;
diagnostic_ranges is a range-specs which we feed the literal position, some
markup and the diagnostic message from the language server. Clarify that in
the comment. No test, but reproducible with gopls:
printf 'package main\nimport "encoding/json"' > test.go
kak -e 'lsp-inlay-diagnostics-enable global; lsp-enable' test.go
Fixes #352
@ul I don't think I have write access yet, otherwise I'd push directly to master if I'm confident in a change.

Escape inlay diagnostics that contain double quotes

---

rc/lsp.kak

Hi! I've made this change in order to fix #390 and #370. The new regex still matches all the current placeholders' formats and additionally matches `gopls` style placeholders (`${1:}`).
Please tell me if everything is OK.

Add support for gopls and Dart lsp placeholders

---

src/diagnostics.rs
src/editor_transport.rs
src/language_features/ccls.rs
src/language_features/clangd.rs
src/language_features/codeaction.rs
src/language_features/cquery.rs
src/language_features/goto.rs
src/language_features/hover.rs
src/language_features/rust_analyzer.rs
src/language_features/semantic_highlighting.rs
src/language_features/semantic_tokens.rs
src/position.rs

This patch makes use of `eval -verbatim` so there is no need to call [editor_quote](https://github.com/kak-lsp/kak-lsp/blob/07f092ed37712534c7ac3fc2117b54da7a9d94cd/src/util.rs#L114) for subsequent command. Side effect is some performance gain, as no extra allocation is done for each `to_editor` command call.
I've tested mostly with `rust-analyzer` and found no regression or any errors.

make use of eval -verbatim and cosmetic patch

---

src/context.rs
src/controller.rs
src/editor_transport.rs
src/language_features/ccls.rs
src/language_features/codeaction.rs
src/language_features/formatting.rs
src/language_features/range_formatting.rs
src/language_features/semantic_highlighting.rs
src/main.rs
src/text_edit.rs
src/types.rs
src/util.rs

This PR brings some optimization as changing type of `EditorResponse.command` form `String` to `Cow<'static, str>`, which I believe won't allocate if called like `ctx.Exec(meta, "slice str")`.
PS: feel free to reject or cherry pick something.

EditorResponse.command form String to Cow<'static, str> and related refactoring

---

kak-lsp.toml

I guess kakoune is not able to implement the proc macro expansion (yet?)
So this can save a lot of headaches for rust-analyzer users

rust: fix "unresolved proc macro" warning

---

rc/lsp.kak

Some request like `update-semantic-highlighting`, `rust-analyzer/inlayHints` and `textDocument/semanticTokens/full` produce `eval -buffer ...` command which gets concatenated with `eval -client ...` so end result is recursive `eval` command, like for example:
```
eval -client client0 -verbatim -- eval -buffer '/Users/vbauer/projects/tmp/inlay-test/src/main.rs' -verbatim -- set buffer rust_analyzer_inlay_hints 1 '2.15+0|{InlayHint}{\}: String', module: kak_lsp::editor_transport:84
```
Having commands like `eval -client ... eval -buffer ..` is redundant despite it works. I think client information is not necessary as long as there is known buffer in context.
So removing `client` parameter from aforementioned requests will produce single `eval` command which works as before, but avoids …

no need to pass client where buffer context is known

---

CHANGELOG.md
src/general.rs

I'm not sure if this will break other language servers - since both rootPath and rootUri are deprecated, pyright only supports rootPath, but not rootUri, so this was essential in getting pyright working. However, kak-lsp should be moving to workspaceFolders going forwards. I tried it but could not get it working, so hopefully this will do.

Add rootPath for backward compatibility

---

kak-lsp.toml

The https://github.com/ocaml-lsp/ocaml-language-server project has been archived, it is not receiving updates anymore.
https://github.com/ocaml/ocaml-lsp is the currently supported "blessed" LSP server (note how it's under the ocaml org).
Its executable is called ocamllsp and it only supports stdio mode (there's no stdio flag).

Change ocaml command to ocamllsp

---

src/thread_worker.rs

This commit fixes the following warning that occurs during compilation:
```
warning: panic message is not a string literal
--> src/thread_worker.rs:29:24
|
29 |                 panic!(e)
|                        ^
|
= note: `#[warn(non_fmt_panic)]` on by default
= note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
|
29 |                 panic!("{}", e)
|                        ^^^^^
help: or use std::panic::panic_any instead
|
29 |                 std::panic::panic_any(e)
|                 ^^^^^^^^^^^^^^^^^^^^^^
warning: 1 warning emitted
```

Fix warning during compilation

---

src/controller.rs
src/workspace.rs

This implements the `workspace/configuration` server request.
This fixes newer LSP implementations that ignore the content of a `workspace/didConfigurationChange` notification and request configuration explicitly.
Tested with https://github.com/sumneko/lua-language-server.
Fixes #479.
Ref #234.

Implement WorkspaceConfiguration request

---

README.asciidoc

Looks like the second occurrences of v9 in lines were missed in the search-replace.

Fix download version in installation instructions

---

CHANGELOG.md
rc/lsp.kak
src/language_features/codeaction.rs

Closes issue #367
For example, this allows to always run "Organize Imports", like so:
define-command -override -hidden lsp-show-code-actions -params .. %{
evaluate-commands %sh{
while [ $# -gt 0 ]; do
title=$1
command=$2
shift
shift
if [ "$title" = "Organize Imports" ]; then
printf %s\\n "$command"
exit
fi
done
}
}

Provide lsp-show-code-actions, to customize the menu behavior on code actions

---

CHANGELOG.md
kak-lsp.toml

I added default settings for julia support. Requires `LanguageServer, StaticLint, SymbolServer` installed globally in julia. Activates the `project=@.` environment. This means that it searches recursively upwards for a julia Project.toml

add default julia setting in kak-lsp.toml

---

CHANGELOG.md
README.asciidoc
rc/lsp.kak

These commands work for any grep-like buffer - the user just needs to pass
`%val{bufname}` as first argument for example `*goto*`, or `*grep*` [1].
I find this very convenient because it makes it trivial to define a command
that allows to go to the next/previous location in any kind of grep buffer.
This works for all lsp buffers with filetype `lsp-goto` as well as for `grep`,
`lint` and `make` buffers:
declare-option -hidden str last_used_grep_buffer
hook -group my global WinDisplay \
\*(?:diagnostics|goto|find|grep|implementations|lint-output|make|references|symbols)\* %{
set-option global last_used_grep_buffer %val{bufname}
}
map global normal <c-n> %{: lsp-next-location %opt{last_used_grep_buffer}<ret>} -docstring 'lsp next'
map global normal <c-p> %{: lsp-previous-location …

Expose lsp-{next,previous}-location to traverse any grep-like buffer

---

CHANGELOG.md
README.asciidoc
kak-lsp.toml
rc/lsp.kak
src/settings.rs
src/types.rs
src/workspace.rs
test/gopls-dynamic-settings.sh

"settings" replaces "initialization_options".
It can be set in kak-lsp.toml, or dynamically in %opt{lsp_config}.
"settings" uses the same structure as VSCode's settings.json. This
means we can properly implement workspace/configuration.
Initialization options and parameters for didChangeConfiguration are
computed by looking up a server-specific section. This seems to match
the expected behavior for all language servers I tried.
Includes configuration for all default language servers (largely
untested). These are default configurations according to the servers'
documentation. I'm not sure how to handle these in future;
- leaving them uncommented has the upside that we'll quickly find errors
- however, the downside is that we shadow the server's actual default
configuration
- additionally …

Mimic VSCode server settings to support workspace/configuration

---

CHANGELOG.md
README.asciidoc
rc/lsp.kak
src/diagnostics.rs

It seemed odd to me that `kak-lsp` showed hints and infos as warnings instead of what they actually are, so I added hints and infos properly. Infos are colored blue by default, and hints are cyan (I wanted to make them grey, but there isn't a standard grey color).
I also took the opportunity to split the `LineFlagErrors` option into `LineFlag(Error|Warning|Info|Hint)`. The `flag-lines` highlighter now uses the `default` face, and `kak-lsp` adds the appropriate markup strings to color them.
The result is as thus:
(pictured with the improved inlay diagnostics from #515, and my [one-darker](https://github.com/raiguard/one.kak) color scheme)
The new diagnostic types work in the diagnostics buffer as well:

Add hint and info diagnostics

---

CHANGELOG.md
rc/lsp.kak
src/diagnostics.rs
src/types.rs

Currently, inlay diagnostics are shown all in a row, one after the other. This makes them very difficult to digest when there are a lot of them.
Neovim's new built-in LSP client does inlay diagnostics in a way that I immediately loved, so I have implemented it here. The following changes were made:
- Added a five-space gap between the actual line and the diagnostics (this can be changed via the `lsp_inlay_diagnostic_gap` option)
- Added a symbol (`lsp_inlay_diagnostic_sign`) that is shown for each diagnostic on the line, and is colored accordingly
- Only the first line of the first diagnostic is printed
**Before:**
**After:**
I'm still fairly new to Rust, so I fully expect my code to be ripped apart and destroyed. It works just fine, but it turns what was a single pass into two passes, …

Consolidate inlay diagnostics

---

rc/lsp.kak

Prior to this patch, attempting to jump to a file from the diagnostics buffer using an absolute path would result in an error such as: `File does not exist: /home/user/project//home/user/project/src/lib.rs`. The buggy behaviour is a result of interaction of numerical registers with the `s` key. This PR fixes the behaviour by immediately moving the `lsp_location_format` regex matches to `abcd` registers, where they can be safely stored. The original contents are, of course, restored after kak-lsp is done with the jump.

Fix diagnostic jumping behaviour

---

rc/lsp.kak

I reckon diagnostic flag-line face should default to `LineNumbers` face to match any colorscheme.
Fixes #524

Use LineNumbers face for diagnostic flag-lines

---

src/text_edit.rs

Extend "remove_adjacent" to include non-empty replacements.  The attached
test case was extracted from a rust-analyzer example. It's not minimized
but the fix is simply that "lsp-replace-selection 'println'" is recognized
to merge with its adjacent (right) neighbor.
Also change the logic for "remove_adjacent" from
(empty && adj1 || adj2) to (empty && (ajd1 || ajd2).
This is arguably more correct.
Because we now recognize more merged selections, we must take care of a
special Kakoune behavior: "|" commands that change nothing preserve selections.
This messes with our logic that would assume they would merge (and go away).
Luckily, we can just drop them since they are redundant.  This causes harmless
changes to the existing test.
Part of #527
Unfortunately, there is another special quirk in …

Fix check if text edit replacement will merge selections

---

CHANGELOG.md
README.asciidoc
rc/lsp.kak
test/rust-analyzer-code-actions.sh
test/rust-analyzer-inlay-code-actions.sh
test/typescript-language-server-code-actions.sh

With the default idle_timeout of 50ms we send quite a lot of requests (#429,
#394), in particular with the recent additions to request for code actions
when idle.
When making nontrivial changes that break the build of the kak-lsp
project, the code action requests seem to keep rust-analyzer maxing
out 1-2 CPUs for a while, even causing some lag in the editor UI
(at least with a debug build of kak-lsp).
The lightbulb is not worth the risk of breaking basic functionality
(like go-to-definition), so disable it by default. Add option
lsp_auto_show_code_actions to enable sending requests.

Do not request code actions by default

---

rc/lsp.kak
src/language_features/hover.rs
src/types.rs

Cleanup: remove some unused/redundant code related to #557
- We don't ever use `HoverModalParams` from the editor so we should just remove the ability to pass in parameters to kak-lsp. We never need to _use_ the serialization as of now. 
- `style` is no longer used
- `context` comes with `struct HoverModalParams` so it can be removed
- We never need to serialize/deserialize the struct `HoverModal`
If we every find a use for these things they can be added again.

Cleanup: remove some unused/redundant code related to #557

---

rc/lsp.kak
src/context.rs
src/controller.rs
src/general.rs
src/main.rs
src/progress.rs
src/types.rs

The previous support was added for rust-analyzer and rust-analyzer started using $/progress, so I don't think anyone's using the old support anymore.
`lsp-cancel-progress` isn't very useful unless someone writes a bit of an involved config for it now, but there could be a future `lsp-cancel` that shows a menu of actions to cancel. I haven't implemented that because I haven't encountered a cancellable progress item yet.
This should be the new wiki page for https://github.com/kak-lsp/kak-lsp/wiki/Handling-progress-notifications if this is merged:
~~~
To handle progress notifications, override the `lsp-handle-progress` command. For example:
```
declare-option -hidden str modeline_progress ""
define-command -hidden -params 6 -override lsp-handle-progress %{
set global modeline_progress %sh{ …
```

Remove window/progress support and add $/progress support

---

README.asciidoc

This commit allows kak script codeblocks and shell script code blocks in `README.asciidoc` to get some syntax highlighting. 
When viewed on GitHub it looks a bit nicer!

Syntax highlighting for `README.asciidoc` codeblocks

---

kak-lsp.toml

It works as intended.
The `info.rkt` file is equivalent of `
CMakeLists.txt` or `Cargo.toml`. It indicates the root of projects.
https://docs.racket-lang.org/raco/info_rkt.html

add racket lsp config

---

README.asciidoc
rc/lsp.kak
src/language_features/document_symbol.rs
src/types.rs

The new next/prev symbol feature is typically used to jump around
functions. We even provide a convenience wrapper with a default
mapping. Some programming styles use mostly methods instead of
functions. To make the default mapping more useful, extend it to
jump to functions *or* methods, instead of just methods.  Delete the
convenience wrapper for methods, since that's now superseded.
Swap the argument order of lsp-next-symbol and friends, so we
can take a variable number of symbol kinds.
Currently depends on the proposed https://github.com/gluon-lang/lsp-types/pull/223

Teach next/prev symbol function to allow multiple symbol kinds

---

src/diagnostics.rs
test/clangd-diagnostic-gutter.sh

By surrounding the different line-specs with single quotes, we enable the use of whitespace for the `lsp_diagnostic_line_error_sign`, `lsp_diagnostic_line_hint_sign`, `lsp_diagnostic_line_info_sign`, `lsp_diagnostic_line_warning_sign` options.
This is necessary to allow for some breathing room between the lsp-error and other gutters (eg. line-numbers).
As an example use-case: I use nerd-font icons as my symbols, but they are wider than an actual character and thus I need to add a whitespace character afterwards. Otherwise the icon overlaps the line-numbers

Allow whitespace in gutter signs

---

Cargo.lock
Cargo.toml
rc/lsp.kak
src/controller.rs
src/language_features/mod.rs
src/language_features/texlab.rs

New commands:
- `texlab-build` - request `textDocument/build` from texlab
- `texlab-forward-search` - request `textDocument/forwardSearch` from texlab
I implemented the commands based on the language_features modules of
rust-analyzer and ccls.
I can't confirm whether these changes are correct, since the master branch of kak-lsp currently crashes for me with texlab.
I need to file an issue for that and investigate.
I just configured kak and kak-lsp today and well in love with kakoune's simple, yet powerful featureset.
Therefore I am neither particulary experienced with kakoune, nor with this codebase.
Any help is appreciated.

Add support for custom texlab commands

---

README.asciidoc
rc/lsp.kak
src/controller.rs
src/general.rs
src/language_features/mod.rs
src/language_features/selection_range.rs
src/types.rs

This adds support for selecting interesting ranges around the cursors.
Usually the ranges correspond to AST nodes.  Add a lsp-selection-range
user mode no quickly navigate the ranges.
The VSCode UI is a bit different, it just needs Alt+Shift+{Left,Right},
whereas we need ":enter-user-mode lsp<ret>v" followed by j/k.
We also allow to navigate outside the user mode using
lsp-selection-range-select, but we don't yet have a way to
automatically request ranges whenever we need them (like VSCode).
We should try to do that, by simply requesting new ranges whenever the
cursor positions are outside the cone of the previously fetched ranges.
Backstory:
I started looking into this feature because I wanted to implement
Kakuone text objects for functions and type definitions (generalizing …

Implement textDocument/selectionRange

---

kak-lsp.toml

While forward search magically works across sessions, inverse search
only works for the session that spawned the PDF preview process,
because inverse search relies on the environment variable $kak_session
to talk to Kakoune. That's good enough for many workflows.
While at it, link to texlab docs for configuring SyncTeX for various
PDF viewers.
See the discussion in #573

Enable SyncTeX inverse search in texlab default config (zathura)

---

kak-lsp.toml

rust-analyzer has much more features than rls and it keeps getting
better. It has been pretty stable recently.  Let's encourage users
to make the switch. Keep around a commented rls config, just in case.

Use rust-analyzer over rls as default language server for Rust

---

README.asciidoc
kak-lsp.toml
src/general.rs
src/language_features/semantic_tokens.rs
src/types.rs

In our config, each entry takes up 5 lines.  Since some language
servers (like rust-analyzer) provide a large number of tokens (>30),
this means that a semantic token configuration quickly exceeds the
size of a terminal window, which makes it a bit less convenient to
skim/read/edit.
We can already use [TOML Inline
Tables](https://github.com/toml-lang/toml/blob/master/toml.md#user-content-inline-table)
to use only one line for each token-face-rule.
However, that would mean we'd need to write something like
semantic_tokens = [ ... ]
which we can only write at the beginning of kak-lsp.toml (because it
must be inside the nameless global TOML table).  I'd like to keep the
semantic tokens configuration at the bottom of this file because unlike
server configuration, this feature is not required …

Write semantic tokens config with one rule per line using inline tables

---

README.asciidoc
rc/lsp.kak
src/controller.rs
src/language_features/document_symbol.rs
src/types.rs

lsp-{next,previous}-{function,symbol} - bound to "[]{}90()" in the
lsp user mode have proven useful to my workflow. Let's expand on
these ideas with an approach that is more native to Kakoune: text
objects.
Introduce lsp-text-object, which moves similar to ]p, ]( and friends,
except it matches LSP symbol ranges.
New object mode mappings were chosen to not collide with any of
another plugin, https://github.com/Delapouite/kakoune-text-objects
"\<a-a>" is a convenience alias for "a", since "\<a-a>a" is awkward
to type.
]a selects from the cursor to the end of a symbol, similar to ]p.
The alternative behavior is \<a-]>a, which selects only the symbol.
Maybe they should be switched, since we already have }a which is
close to first behavior?
The surrounding modes \<a-a> and \<a-i> only select …

Introduce text objects for selecting functions and other symbols

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.asciidoc
rc/lsp.kak
src/controller.rs
src/general.rs
src/language_features/inlay_hints.rs
src/language_features/mod.rs
src/language_features/rust_analyzer.rs

Close #600 
For now this doesnt remove the old rust-analyzer api, and adds both the `textDocument/inlayHint` and `experimental/inlayHints`. The former is proposed for LSP v3.17, and the latter is the temporary name used for the proposed api by rust-analyzer.
I think we should remove both old apis when the new one is standardized, and adapted by rust-analyzer, since i have seen no indication that other servers have used the rust-analyzer or experimental prefix versions.

Add textDocument/inlayHint and experimental/inlayHints

---

src/controller.rs
src/language_server_transport.rs
src/types.rs

Justification and use case in #606; closes #606.
I chose the name `envs` since it's what Rust uses and seems reasonable, but can rename depending on what's desired.

Add envs parameter to language config

---

rc/lsp.kak

This seems like the better default.
See the discussion in https://discuss.kakoune.com/t/sane-kak-lsp-config-hook/2019

Disable inlay diagnostics in insert mode

---

CHANGELOG.md
README.asciidoc
rc/lsp.kak
src/controller.rs
src/language_features/inlay_hints.rs

rust-analyzer recently switched to the standard implementation.
https://github.com/rust-lang/rust-analyzer/pull/11935
See #600 for more info

remove rust-analyzer inlay-hints implementation

---

README.asciidoc

Its been a long time since ive used snippets, and they have been broken for me for a while, so i spent some time fixing it while listening to the new kendrick album :)
- Snippets are now only fully expanded when the completions menu is closed, making them much more robust
- The text that is inserted until the menu is closed is the snippets contents merged onto one line and with tabstops (cursor jump points) replaced with their placeholder text.
These two things result in a pretty smooth snippets experience, that is a lot more practical than the old implementation, while staying fairly simple.
Currently, i have only tested with rust-analyzer, but it should be better than the old implementation everywhere.
At some point i would like to rewrite the placeholder selection and location jumping, …

Fix snippets

---

kak-lsp.toml

Filetype plugin for Elvish is part of Kakoune's repo
(https://github.com/mawww/kakoune/blob/master/rc/filetype/elvish.kak), so it
would make sense for kak-lsp to have a default config for Elvish too.

Add configuration for Elvish.

---

src/session.rs

To reproduce, run `lsp-formatting-sync` on a file without a configured lsp server.
I think this works for all the blocking commands I see in `lsp.kak`. I'm not sure what's appropriate for `write_response_to_fifo = true` calls, but I figure this is better than deadlock.
I'd like to add more visibility to other error conditions, but if a `lsp-show-error` triggers on _every_ request that fails due to a missing lsp configuration, it could bother auto hover users. Maybe that could be solved with a smarter auto hover implementation?

Fix blocking request hanging if unconfigured

---

README.asciidoc
rc/lsp.kak

When snippets are enabled, we can type
openat<c-n>somefd<tab>somefile<tab>O_CREAT,<space>0644
to get
openat(somefd, somefile, O_CREAT, 0644)
Very fancy.
Sadly, I often can't fill in all arguments without looking
around or fixing some other code.  If I stop somewhere in
the middle, highlighting remains, and can only be cleared
with `lsp-snippets-select-next-placeholders`.  For example
`openat<c-n><esc>` gives
openat(%(), const char *file, int oflag, ...)
where the tail of arguments is still highlighted.  This is supremely
annoying because I usually don't want to simply resume where I left
of.
Also, the last snippet-placeholder is usually after the closing
parenthesis. Jumping there makes sense when staying in insert mode
throughout but not when when exiting insertion mode halfway through …

Disable completion snippet placeholders when leaving insert mode

---

CHANGELOG.md
README.asciidoc
kak-lsp.toml
rc/lsp.kak

By convention, Kakoune plugins do not add their own key mappings.
This makes them more predictable and avoids clashes with the user's
mappings.  This is especially important as we add more mappings,
for example the suggested binding for `<tab>`.
Let's add a "suggested mappings" section, so new users are less likely
to skip mapping `<tab>` (which is quite important for snippets).
Keep keys like "gd" to avoid breakage (also no one has complained
about them). Not sure if we should keep the object mode keys.

Add section with suggested mappings instead of mapping keys ourselves

---

README.asciidoc
rc/lsp.kak

Helix provides a default mapping for jumping to next/previous error. It
is pretty useful when you know that the current buffer has errors,
so we should at least have a recommended mapping.
Add recommended mappings to the object mode. This is a bit hacky
because they don't select _until_ the error but move the entire
selection, independent of object mode key. However it has the advantage
that users are already familiar with choosing a direction with [ or ].

Recommend mappings to jump to next/previous diagnostic

---

src/context.rs
src/editor_transport.rs
src/session.rs
src/workspace.rs

Hey! I rolled with [the idea of reporting errors for only calls that happen outside of hook context](https://github.com/kak-lsp/kak-lsp/pull/630#issuecomment-1191106482), and I think it works pretty well so far. I haven't gotten to unsupported requests yet, but I added the error cases I ran into from bad config and flaky lsp servers. I also removed some panics after I brought down `kak-lsp` a few times.
The hook detection relies on a bit of a hack. From what I can tell, [`%val{hook_param}` is always set when running in a hook, though it's empty for hooks that don't have a hook_param](https://github.com/mawww/kakoune/blob/e83dbdcd2cbddb30ac63ec503c76b46b80ffe44d/src/hook_manager.cc#L114). I was thinking of asking for a more official way to detect if we're running in a hook or not in …

Show more errors in the editor

---

Cargo.lock
Cargo.toml
src/capabilities.rs
src/context.rs
src/controller.rs
src/text_sync.rs

Some language servers request to be notified of changes files in the
workspace (even if they are not open by the editor). This includes
build configuration files like Cargo.toml, for which we currently do
not send any notification, not even when it's opened by the editor.
Fix these problems for the common cases by watching the entire root
path recursively for file change events and forward them to the server.
Batch event notifications that arrive within a window of 500
milliseconds, to reduce traffic in the event of a "git checkout"
or "git rebase".
This feature might cause performance problems on large worktrees.
Tested with rust-analyzer, are there any other servers that request
these file change notifications?
This means we send duplicate change notifications when saving a file
(since …

Notify server of workspace changes via workspace/didChangeWatchedFiles

---

kak-lsp.toml

The links old links that are in the comment were leading to 404 error

latex: update links to texlab docs which were moved to wiki

---

rc/lsp.kak

I created a fresh window via `:new`, the client name was `client1`. Then I did
`:set global docslient 'client1'`
I expected to see any hover triggered from `client0` appear in `client1`. However that did not happen. 
This commit should fix the issue.

Fix for hover in docsclient not working

---

kak-lsp.toml

In the case of GHC, the root would be incorrectly detected, leading to a non-functional HLS instance. `hie.yaml` and `cabal.project` are AFAICT the most reliable indicators of where the project root is.

Change roots for Haskell

---

kak-lsp.toml

For instance, seeing a `dune-workspace` file is a very good indicator to have found the project root. OTOH seeing a `dune` file is a not a good indication of being in the root as dune files will often appear  much below the root.

kak-lsp.toml: Improve `roots` for OCaml

---

Cargo.lock

update to crossbeam-channel v0.5.8 as v0.5.6 in the `crates-io` registry is yanked
Fix for:
```
$ cargo install --path . --locked
Installing kak-lsp v14.2.0-snapshot (/home/abcxyz123/kak-lsp)
Updating crates.io index
warning: package `crossbeam-channel v0.5.6` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
...
```

update to crossbeam-channel v0.5.8 as v0.5.6 in the `crates-io` registry is yanked

---

src/language_features/code_action.rs
src/language_features/completion.rs

This depends on a proposed Kakoune patch <s>https://github.com/mawww/kakoune/pull/4813</s> https://github.com/mawww/kakoune/pull/5035

Sort important completions and code actions first

---

src/show_message.rs

I'm not sure [these lines were needed](https://github.com/kak-lsp/kak-lsp/commit/6ac4d3c585000270d837bfa1941c71218f32ee75#diff-8aa30bdbc7cfcdda8ea817f73e23e7e1257d81c5edcc7e604bb36be6ccc36310R85-R92).
At least it broke the Scala Metals LSP integration for me.
Reverting those lines resolved the issue.
```toml
[package]
name = "kak-lsp-reproduce-toml-bug"
version = "1.0.0"
[dependencies]
lsp-types = { version = "0.95.0", features = ["proposed"] }
serde = "1.0.0"
toml = { version = "0.8.8", features = ["display"] }
```
```rust
use serde::ser::Serialize;
fn main() {
let item = lsp_types::MessageActionItem {
title: "some title".to_string(),
properties: std::collections::HashMap::new(),
};
let mut s = String::new();
item.serialize(toml::ser::ValueSerializer::new(&mut s)).unwrap();
println!("New …
```

window/showMessageRequest: fix invalid action item serialization

---

rc/lsp.kak

Otherwise the `on-abort` action stays in the `@args` :P

menu: Shift args twice when on-abort is encountered

---

rc/lsp.kak
src/diagnostics.rs

Use the new [`flag-lines -after`](https://github.com/mawww/kakoune/commit/c124c8f517c921bee2017cdf5081f3e8b98e27b9) feature to massively improve inlay diagnostics. No longer will they sporadically draw in the middle of a line and no longer will the cursor be affected by them!
**Before:**
**After:**

Use `flag-lines -after` for inlay diagnostics

---

README.asciidoc

Hello, I have renamed the Arch package, as per the encouragement in the latest changelog :slightly_smiling_face: 
https://archlinux.org/packages/extra/x86_64/kakoune-lsp/

Update Arch pkg name

---

kak-lsp.toml

**Inlay hints:**
Since the [1.3.0](https://scalameta.org/metals/blog/2024/04/15/thalium)
Metals switched from their so-called custom Decoration LSP extension to
LSP-native inlay hints.
These flags are need to be explicitly enabled on the server's side.
**Notifications via `window/showMessage:`**
Turns out `kak-lsp` supports the `window/showMessage`.
It's more convenient than the previous `window/logMessage` as it prints
the status into the Kakoune's status bar.

Scala Metals default config improvements

---

src/main.rs

If a legacy config has multiple languages that use the same language server command (e.g. typescript & javascript both using vtsls), then one of them would overwrite the other, with the winner depending on hash iteration order. To fix this, we can just add the language ID to the configured server name to ensure both entries are separate.
Note that this will end up running an independent language server for each language ID, but that behavior seems to match what pre-v15 did anyway.

Fix multiple legacy languages w/ same language server clashing

---

src/diagnostics.rs

I don't know why, but servers like clangd provide
diagnostic messages with trimming whitespace,
which messes up with the formatting a little
when seeing the message on hover.

Trim end of diagnostic message on hover

---

Cargo.lock

In Rust 1.80.0, the version of the `time` crate included in `kakoune-lsp` no longer builds. These links have more detail.
- https://github.com/rust-lang/rust/issues/127343
- https://internals.rust-lang.org/t/type-inference-breakage-in-1-80-has-not-been-handled-well/21374
I've run `cargo update`, then `cargo build` and `cargo test` and done a smoketest.
I think everything's looking OK after this update.

chore(deps): run cargo update to fix Rust 1.80 build

---

kak-lsp.toml

`pyproject.toml` is used by most python package managers and tools to find the root of a project.

Add `pyproject.toml` as root for python LSPs

---

rc/servers.kak

gopls: ui.completion prefix is not required

---

rc/servers.kak

As reported in [^1], we have configured Scala Metals to use Unicode
symbols for window/showMessage which are displayed in the status line.
Kakoune does not yet know that emoji are width 2, which causes visual
glitches.
Unfortunately fixing Kakoune is not completely trivial because they
don't use wcswidth() but only wcwidth(); this means that we'd need to
adjust the code to lookahead by one codepoint to detect any VARIATION
SELECTOR-16.
Until we fix this, let's switch back to the defaults, e.g. no emoji.
Alternatively, we could use logMessage to move away from the status
line into the debug buffer but that has the same problem, it's just
less visible.
cc @igor-ramazanov
[^1]: https://github.com/kakoune-lsp/kakoune-lsp/pull/794#discussion_r1821986637

Scala Metals: turn off Unicode icons until Kakoune can handle emoji width

---

rc/servers.kak

Hi!
This PR adds vuejs support. It is based on:
https://www.npmjs.com/package/@vue/typescript-plugin
The reason I set `location` to `vue-language-server` rather than `"/usr/local/lib/node_modules/@vue/language-server"` as documented in the npm package is because the latter won't work with nix.

Add support for vuejs

---

rc/servers.kak

Looks like a typo dropped the `c` here.

Set cmake-language-server for cmake, not make
