kakoune-lsp/kakoune-lsp

rc/lsp.kak
Track the last sent change in a lsp_timestamp option, and only
send didChange (writing the buffer to a tempoary file) if this
does not match the current timestamp.
=> Only send didChange when the buffer did change

rc/lsp.kak
Arithmetic expansion is posix, and slightly slimper/cheaper than calling `expr`
=> use shell arihmetic expansion instead of 'expr'

README.asciidoc
Hello
I followed the way you present the project on reddit annoucements.
It may help user not already familiar with all those terms.
=> add links to LSP, Kakoune and Rust in README

README.asciidoc, rc/lsp.kak
=> Find next or previous error

rc/lsp.kak
=> Remove unnecessary variable lsp_tab_size

rc/lsp.kak
Adds the following commands piggybacking `grep-jump` from `grep.kak`:
- `lsp-references-next-match`: Jump to the next references match
- `lsp-references-previous-match`: Jump to the previous references match
- `lsp-symbols-next-match`: Jump to the next symbols match
- `lsp-symbols-previous-match`: Jump to the previous symbols match
=> Add grep-jump style commands for *symbols* and *references*

kak-lsp.toml
https://github.com/crystal-lang-tools/scry
=> Add support for Crystal

kak-lsp.toml
I've been using these settings for elm for a few days.  So far so good.
=> elm language server settings

rc/lsp.kak
As suggested in https://github.com/ul/kak-lsp/issues/228 I've added two commands `lsp-disable` and `lsp-disable-window`. However after executing those hovering still works for some reason. Did I missed something?
=> add lsp-disable and lsp-disable-window

README.asciidoc
To prevent issues such as #241
=> Document configuration file: overwriting vs extending

README.asciidoc
the correct command is `xbps-install` :)
=> fix void install command

src/language_features/definition.rs
=> Open goto definition in jump client

rc/lsp.kak, rustfmt.toml, src/language_features/completion.rs
Uses slightly modified code from https://github.com/occivink/kakoune-snippets to parse snippets.
=> Add Snippet completion

kak-lsp.toml
=> Add support for Ruby

src/controller.rs
According to the lsp specification [1], "if clients receive a
ClientModified error, it generally should not now it in the UI for
the end-user. Clients can resend the request if appropriate."
Note that this patch doesn't resend the request.
Since there's only one language-server error that we recognize, this
patch hard-codes it. There are currently two lsp-specific error codes,
so it doesn't make sense to pull in any dependencies for their
definition. If it ever does, the "lsp-server" crate exports the error
codes.
[1] https://microsoft.github.io/language-server-protocol/specification
=> Don't display an error message for a CONTENT_MODIFIED error.

src/position.rs
Currently, kak-lsp panics if a language server sends an out-of-bound range of characters.
This broke `lsp-formatting-sync` with `dhall-lsp-server`, which deliberately uses an out-of-bound value to convey that the whole file should be replaced:
https://github.com/dhall-lang/dhall-haskell/blob/431f8cfdd6af6c0a09a1a1f2f8056202b6e02a8c/dhall-lsp-server/src/Dhall/LSP/Handlers.hs#L307
Instead of panicking, the range is now clamped to the size of the file.
=> Fix crash when language server sends out-of-bounds range

src/project_root.rs
=> Skip non-existent directories when looking up the project root path

rc/lsp.kak
Fixes https://github.com/ul/kak-lsp/issues/322
=> Fix incorrect scope for lsp_semantic_tokens

rc/lsp.kak, src/controller.rs, src/language_features/references.rs
This is my (tested and working) first attempt at a fix for #120.
I'm happy to revise the code structure if desired.
=> Replace referencesHighlight with documentHighlights

src/diagnostics.rs
The previous separator insertion assumed that a diagnostic would only span one line, and when it wouldn't, it would add commas even when one diagnostic was the first on its line.
=> Inlay diagnostics: fix bugged separators when diagnostics span multiple lines

src/general.rs
This actually adds a few things we previously weren't asking for, so
it might actually give us some free new features for language servers
that were checking that. It also makes for a good place to find more
things to work on! There's still a lot that can be improved.
=> Fill out all client capabilities manually

src/diagnostics.rs, src/language_features/rust_analyzer.rs, src/types.rs, src/workspace.rs
Haven't tested it much yet. rust-analyzer's actions are *super* useful, so this is a pretty big improvement for me at least :)
Closes https://github.com/ul/kak-lsp/issues/314
=> Support custom command rust-analyzer.applySourceChange

src/language_features/rust_analyzer.rs
Seems like an improvement, didn't know about it before.
=> use :edit for rustAnalyzer.applySourceChange

src/general.rs, src/language_features/rust_analyzer.rs, src/workspace.rs
It compiles, but I haven't tested it yet.
=> Improve failure handling in workspace::apply_edit

src/position.rs
In some cases (presumably caused by the LSP asynchronously responding, while editing text) it seems that `kak-lsp` can get confused, causing it to try to index into out-of-bounds ranges. This is
easily reproducible by taking e.g. `rust-analyzer`, opening a rust file, and just mashing on the keyboard. (especially editing `use` lines causes this, in my experience.) This partially resolves this by catching these out-of-range positions and translating them to similarly invalid ranges on the other end.
This isn't a comprehensive fix (I believe the UTF-8 codepoint handling is still partially broken),
but this seems to resolve a decent amount of crashes that I have personally encountered
using `rls`, `rust-analyzer`, and `gopls`. Properly bailing out would be preferred, but this would require …
=> Fix panics on out-of-range codepoints

src/project_root.rs
Introduced in c13cea5fedc.
Fixes #382
=> Fix infinite loop when editing scratch buffer

rc/lsp.kak
Same fix as described here: https://github.com/mawww/kakoune/pull/3656
=> bring tools buffers to front in context of toolsclient

src/diagnostics.rs, src/language_features/ccls.rs, src/language_features/cquery.rs, src/language_features/formatting.rs, src/language_features/goto.rs, src/language_features/highlights.rs, src/language_features/range_formatting.rs, src/language_features/rust_analyzer.rs, src/language_features/semantic_highlighting.rs, src/language_features/semantic_tokens.rs, src/position.rs, src/text_edit.rs, src/types.rs, src/util.rs
Not that it makes a difference, but this feels less surprising.
=> Refactor: pass enum OffsetEncoding by value

README.asciidoc, kak-lsp.toml
https://github.com/kak-lsp/kak-lsp/blob/2e1f9b62df71d2a641e0a8b33c30df15da8478d3/src/types.rs#L28
=> Fix docs on semantic token modifier config

kak-lsp.toml
Project is here: https://github.com/elixir-lsp/elixir-ls
=> Add elixir-ls to kak-lsp.toml

README.asciidoc, rc/lsp.kak
I think it fits the user mode very nicely 🙂
=> Add lsp-rename-prompt to the user mode

rc/lsp.kak, src/language_features/completion.rs
=> terminate info cmds with --

src/language_features/completion.rs
The first commit of the branch mentioned in https://github.com/kak-lsp/kak-lsp/issues/40#issuecomment-663838631.
=> completion: fix "simple textEdit" detection for non-ASCII chars

CHANGELOG.md, README.asciidoc, rc/lsp.kak, src/diagnostics.rs, src/language_features/goto.rs, src/util.rs
This is solution ~~2~~ 5 from #406
=> Don't change kakoune's directory with diagnostics/goto

rc/lsp.kak
Should work on the html tags now.
=> Fix snippet injection, once again.

src/language_features/hover.rs
=> Reset hover diagnostics face

kak-lsp.toml
Using the standard https://github.com/REditorSupport/languageserver/
Tested, working as expected
=> add config for R language server

README.asciidoc, rc/lsp.kak, src/controller.rs, src/general.rs, src/language_features/call_hierarchy.rs, src/language_features/mod.rs, src/types.rs
=> Basic support for call hierarchy

src/language_features/hover.rs, src/markup.rs
=> escape backslash for kak markup

src/language_features/document_symbol.rs
Currently _previous_ symbol goto/hover is not working properly for documents with nested children.
E.g. Open up kakoune source `src/input_handler.cc` line 227 (Use kakoune `08d2a8ba63f9f0fbabf6a6221531afc91698fc20`). (I assume that you are using clangd) 
**Actual**
Hover of the previous symbol i.e. `<lsp> [` will show you `Namespace Kakoune`
**Expected**
It should be `Method on_disabled`
This PR fixes this issue.
=> Order of checking exceeds() matters if we are searching forward or backward

rc/lsp.kak, src/language_features/completion.rs, src/types.rs
This currently requires Kakoune built with https://github.com/mawww/kakoune/pull/4418.
Closes #444
=> Support filterText in completions

rc/lsp.kak
I think it is enough to send didChange synchronousy to fix #267. I've only tried it with pyright so there might be some issue together with other language servers.
=> Send did change synchronously to address #267

kak-lsp.toml
Closes https://github.com/kak-lsp/kak-lsp/issues/297.
Created by following the [Scala Metals guide](https://scalameta.org/metals/docs/integrations/new-editor) and existing entries in the `kak-lsp.toml`.
=> Add Scala Metals LSP

CHANGELOG.md, rc/lsp.kak, src/language_features/document_symbol.rs, src/language_features/goto.rs
Depends on https://github.com/mawww/kakoune/pull/5027
=> lsp-goto-document-symbol: preview jump target when selecting completion candidates

src/text_sync.rs
This crashes [nil](https://github.com/oxalica/nil), since it defaults to crashing upon getting a notification it doesn't handle.
=> Don't send didSave notifications if server doesn't want it

rc/servers.kak
=> Match all settings tables in servers.kak

rc/servers.kak
1. `"true"` to `true`
2. move `root_globs` option under `[julia-language-server]` heading
=> fix two types in julia lsp configuration
